# Generated by Django 4.1.5 on 2023-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
