# Generated by Django 4.1.5 on 2023-02-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0004_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client',
            new_name='clients_image',
        ),
    ]
