# Generated by Django 4.1.5 on 2023-02-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0005_rename_client_client_clients_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clients_image',
            new_name='image',
        ),
    ]
