# Generated by Django 4.1.5 on 2023-02-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0006_rename_clients_image_client_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='image',
            new_name='client_image',
        ),
    ]
