# Generated by Django 4.1.5 on 2023-02-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0007_rename_image_client_client_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
