# Generated by Django 4.1.5 on 2023-02-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0008_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
