# Generated by Django 4.1.5 on 2023-02-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0011_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
