# Generated by Django 4.1.5 on 2023-02-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0015_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
