# Generated by Django 4.1.5 on 2023-02-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0016_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
