# Generated by Django 4.1.5 on 2023-02-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0018_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('special_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
