# Generated by Django 4.1.5 on 2023-02-23 23:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smproject', '0019_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsgrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngrid_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(default='uncategorized', max_length=20)),
                ('ngrid_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ngrid_description', models.CharField(blank=True, max_length=20, null=True)),
                ('ngrid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
