# Generated by Django 4.1.5 on 2023-02-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smproject', '0021_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parallax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('desc_work', models.CharField(max_length=1000)),
            ],
        ),
    ]
